"""
BugHuntRecon - Markdown Report Generator
"""

import os
from datetime import datetime
from core.utils import read_file_lines


class MarkdownReportGenerator:
    """Generate Markdown reports."""

    def __init__(self, output_dir, target, scan_start, scan_end):
        self.output_dir = output_dir
        self.target = target
        self.scan_start = scan_start
        self.scan_end = scan_end
        self.report_dir = os.path.join(output_dir, "reports")
        os.makedirs(self.report_dir, exist_ok=True)

    def generate(self):
        """Generate the Markdown report."""
        report_path = os.path.join(self.report_dir, "report.md")

        lines = []
        lines.append(f"# 🔥 BugHuntRecon Report\n")
        lines.append(f"**Target:** `{self.target}`\n")
        lines.append(f"**Scan Start:** {self.scan_start}\n")
        lines.append(f"**Scan End:** {self.scan_end}\n")
        lines.append(f"**Duration:** {self.scan_end - self.scan_start if self.scan_end and self.scan_start else 'N/A'}\n")
        lines.append(f"---\n")

        # Statistics
        lines.append(f"## 📊 Summary Statistics\n")

        stats = {
            'Subdomains': ('subdomains/all_subdomains.txt', 0),
            'Live Hosts': ('dns/live_hosts.txt', 0),
            'Open Ports': ('ports/all_ports.txt', 0),
            'URLs': ('content_discovery/all_urls.txt', 0),
            'JS Files': ('content_discovery/js_files.txt', 0),
        }

        lines.append("| Metric | Count |")
        lines.append("|--------|-------|")

        for label, (filepath, _) in stats.items():
            full_path = os.path.join(self.output_dir, filepath)
            count = len(read_file_lines(full_path)) if os.path.exists(full_path) else 0
            lines.append(f"| {label} | {count} |")

        lines.append("")

        # Vulnerabilities
        lines.append(f"## 🚨 Vulnerabilities\n")
        vuln_dir = os.path.join(self.output_dir, "vulnerabilities")
        if os.path.exists(vuln_dir):
            vuln_count = 0
            for root, dirs, files in os.walk(vuln_dir):
                for f in files:
                    if f.endswith('.txt'):
                        vulns = read_file_lines(os.path.join(root, f))
                        vuln_count += len(vulns)
                        if vulns:
                            rel_path = os.path.relpath(
                                os.path.join(root, f), self.output_dir
                            )
                            lines.append(f"### {rel_path}\n")
                            lines.append("```")
                            for v in vulns[:50]:
                                lines.append(v)
                            if len(vulns) > 50:
                                lines.append(f"... and {len(vulns) - 50} more")
                            lines.append("```\n")

            lines.append(f"**Total Vulnerabilities: {vuln_count}**\n")
        else:
            lines.append("No vulnerabilities found.\n")

        # Secrets
        lines.append(f"## 🔑 Secrets & Sensitive Data\n")
        secrets_dir = os.path.join(self.output_dir, "js_analysis", "secrets")
        if os.path.exists(secrets_dir):
            for f in os.listdir(secrets_dir):
                if f.endswith('.txt'):
                    secrets = read_file_lines(os.path.join(secrets_dir, f))
                    if secrets:
                        lines.append(f"### {f}\n")
                        lines.append("```")
                        for s in secrets[:50]:
                            lines.append(s)
                        lines.append("```\n")

        # Subdomains
        lines.append(f"## 🌐 Subdomains\n")
        sub_file = os.path.join(self.output_dir, "subdomains", "all_subdomains.txt")
        if os.path.exists(sub_file):
            subs = read_file_lines(sub_file)
            lines.append(f"Total: {len(subs)}\n")
            lines.append("<details><summary>Click to expand</summary>\n")
            lines.append("```")
            for s in subs[:200]:
                lines.append(s)
            if len(subs) > 200:
                lines.append(f"... and {len(subs) - 200} more")
            lines.append("```")
            lines.append("</details>\n")

        # Live Hosts
        lines.append(f"## ✅ Live Hosts\n")
        live_file = os.path.join(self.output_dir, "dns", "live_hosts.txt")
        if os.path.exists(live_file):
            hosts = read_file_lines(live_file)
            lines.append(f"Total: {len(hosts)}\n")
            lines.append("<details><summary>Click to expand</summary>\n")
            lines.append("```")
            for h in hosts[:200]:
                lines.append(h)
            lines.append("```")
            lines.append("</details>\n")

        lines.append(f"\n---\n*Generated by BugHuntRecon | {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*\n")

        with open(report_path, 'w') as f:
            f.write('\n'.join(lines))

        return report_path